version: "3.8"

services:
  app:
    image: ghcr.io/michracz00/app:latest
    ports:
      - "8080:8080"
    environment:
      - MODEL_SERVICE_URI=http://model-service:8081/
    networks:
      - my-network

  model-service:
    image: ghcr.io/remla24-team-15/model-service:latest
    ports:
      - "8081:8081"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge