version: "3.8"

services:
  app:
    image: michracz00/app:latest
    ports:
      - "8080:8080"
    networks:
      - my-network

  model-service:
    image: michracz00/model-service:latest
    ports:
      - "8081:8081"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge