version: "3.8"
# Remeber to rebuild docker images if you run into
services:
    app:
      image: ghcr.io/remla24-team-15/app:latest
      container_name: app
      ports:
        - "8080:8080"
      environment:
        - MODEL_SERVICE_URI=http://modelservice:8081/
  
    model-service:
      image: ghcr.io/remla24-team-15/model-service:latest
      container_name: modelservice
      ports:
        - "8081:8081"
