apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-alerts
  namespace: monitoring
spec:
  groups:
  - name: app.rules
    rules:
    - alert: HighRequestRate
      expr: rate(http_requests_total[1m]) > 15
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: High request rate