apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../worker_compose.yaml -o ./workers.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: app
      name: app
    spec:
      ports:
        - name: "8080"
          port: 8080
          targetPort: 8080
      selector:
        io.kompose.service: app
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../worker_compose.yaml -o ./workers.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: model-service
      name: model-service
    spec:
      ports:
        - name: "8081"
          port: 8081
          targetPort: 8081
      selector:
        io.kompose.service: model-service
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../worker_compose.yaml -o ./workers.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: app
      name: app
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: app
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f ../worker_compose.yaml -o ./workers.yaml
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.service: app
        spec:
          containers:
            - env:
                - name: MODEL_SERVICE_URI
                  value: http://modelservice:8081/
              image: ghcr.io/remla24-team-15/app:latest
              name: app
              ports:
                - containerPort: 8080
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../worker_compose.yaml -o ./workers.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: model-service
      name: model-service
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: model-service
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f ../worker_compose.yaml -o ./workers.yaml
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.service: model-service
        spec:
          containers:
            - image: ghcr.io/remla24-team-15/model-service:latest
              name: modelservice
              ports:
                - containerPort: 8081
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}

