- hosts: all
  become: yes
  tasks:
    - name: Update apt repository and cache
      apt:
        update_cache: yes

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt package index after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker Engine, CLI, and Containerd
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Create /etc/docker directory
      file:
        path: /etc/docker
        state: directory

    - name: Create docker service directory
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory

    - name: Restart Docker
      systemd:
        name: docker
        enabled: yes
        daemon_reload: yes
        state: restarted

    - name: Add user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes

- hosts: controller_group
  become: yes
  tasks:
    - name: Install k3s server
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" K3S_TOKEN=12345 sh -
      args:
        executable: /bin/bash

    - name: Get k3s node token
      command: cat /var/lib/rancher/k3s/server/node-token
      register: node_token
      become: true

    - name: Save node token
      copy:
        content: "{{ node_token.stdout }}"
        dest: /vagrant/k3s_node_token

    - name: Install Helm dependencies
      shell: |
        curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
        sudo apt-get install apt-transport-https --yes
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm
      args:
        executable: /bin/bash

    - name: Add Prometheus Helm repo
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      args:
        executable: /bin/bash

    - name: Update Helm repos
      command: helm repo update
      args:
        executable: /bin/bash

    - name: Install Prometheus Operator
      shell: helm install prometheus-operator prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace
      args:
        executable: /bin/bash
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Apply Kubernetes YAML files
      shell: |
        kubectl apply -f /vagrant/kubernetes/prometheus.yaml
      args:
        executable: /bin/bash
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- hosts: worker_group
  become: yes
  tasks:
    - name: Fetch node token from controller
      slurp:
        src: /vagrant/k3s_node_token
      register: token_content

    - name: Save node token locally
      copy:
        content: "{{ token_content.content | b64decode }}"
        dest: /tmp/k3s_node_token

    - name: Install k3s agent
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ cont_ip }}:6443 K3S_TOKEN=12345 K3S_NODE_NAME={{ node_name }} sh -
      args:
        executable: /bin/bash

    - name: Apply Kubernetes YAML files
      shell: |
        kubectl apply -f /vagrant/kubernetes/node_deployment.yaml
      args:
        executable: /bin/bash
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml