- hosts: all
  become: yes
  tasks:
    - name: Update apt repository and cache
      apt:
        update_cache: yes

- name: Cluster prep
  hosts: all
  gather_facts: true
  become: true
  roles:
    - role: prereq

- name: Setup K3S server
  hosts: controller_group
  become: true
  roles:
    - role: k3s_server

- name: Setup K3S agent
  hosts: worker_group
  become: true
  roles:
    - role: k3s_agent
