apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  model.host: "http://modelservice:8081/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-depl
  labels:
    app: url-model
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-model
  template:
    metadata:
      labels:
        app: url-model
    spec:
      containers:
      - name: url-model
        image: ghcr.io/remla24-team-15/model-service:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: url-model-serv
spec:
  selector:
    app: url-model
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-app-depl
  labels:
    app: url-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-app
  template:
    metadata:
      labels:
        app: url-app
    spec:
      containers:
      - name: url-app
        image: ghcr.io/remla24-team-15/app:latest
        ports:
        - containerPort: 8080
        env:
          - name: MODEL_SERVICE_URI
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: model.host
---
apiVersion: v1
kind: Service
metadata:
  name: url-app-serv
spec:
  selector:
    app: url-app
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  defaultBackend:
    service:
      name: url-app-serv
      port:
        number: 8080