---
- hosts: controler
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add ansible user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install minikube
      apt:
        deb: "https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb"
        state: present

    - name: Install kubectl
      command: snap install kubectl --classic

    - name: Install helm
      command: sudo snap install helm --classic

- hosts: localhost
  tasks:
    - name: Start minikube
      command: "ssh vagrant@localhost -p2222 minikube start --driver=docker"

- hosts: controler
  tasks:
    - name: Add Prometheus Helm repository
      command: helm repo add prom-repo https://prometheus-community.github.io/helm-charts

    - name: Update Helm repositories
      command: helm repo update

    - name: Install Prometheus stack
      command: helm install myprom prom-repo/kube-prometheus-stack