apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: ghcr.io/remla24-team-15/app:latest
    ports:
    - containerPort: 8080
  - name: model-service
    image: ghcr.io/remla24-team-15/model-service:latest
    ports:
    - containerPort: 8081 