# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Define the controller VM
  config.vm.define "controler" do |controler|
    controler.vm.box = "bento/ubuntu-24.04"
    controler.vm.box_version = "202404.26.0"
    controler.vm.box_check_update = false

    controler.vm.network "private_network", ip: "192.168.56.1"

    controler.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 1
    end
  end

  # Define worker VMs
  num_workers = 2
  (1..num_workers).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = "bento/ubuntu-24.04"
      worker.vm.box_version = "202404.26.0"
      worker.vm.box_check_update = false

      worker.vm.network "private_network", ip: "192.168.56.#{i + 1}"

      worker.vm.provider "virtualbox" do |v|
        v.memory = 6144
        v.cpus = 2
      end
    end
  end
end
